# Generated by Django 4.0.4 on 2022-06-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadmintonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupied', models.TextField(max_length=100)),
                ('nums', models.TextField(max_length=100)),
            ],
        ),
    ]
