# Generated by Django 4.0.4 on 2022-06-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_badmintoninfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badmintoninfo',
            name='nums',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='badmintoninfo',
            name='occupied',
            field=models.CharField(max_length=100),
        ),
    ]
