# Generated by Django 4.0.4 on 2022-06-05 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_badmintoninfo_occupied'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
